// <auto-generated />
namespace RmR.Migrations.ResumeMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullsOnDateResume21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullsOnDateResume21));
        
        string IMigrationMetadata.Id
        {
            get { return "201605170143540_NullsOnDateResume21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
